[package]
name = "goober-bot"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/valentinegb/goober-bot"
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = "0.6.1"
shuttle-runtime = "0.44.0"
# Since poise is a serenity command framework, it can run on Shuttle with shuttle-serenity
shuttle-serenity = "0.44.0"
tracing = "0.1.37"
tokio = "1.26.0"
rand = "0.8.5"
shuttle-common = { version = "0.44.0", features = ["service"] }
