[package]
name = "goober-bot"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = { git = "https://github.com/fgardt/poise.git", branch = "feat/user_apps", version = "0.6.1", features = ["unstable"] }
shuttle-runtime = "0.46.0"
# Since poise is a serenity command framework, it can run on Shuttle with shuttle-serenity
shuttle-serenity = "0.46.0"
tracing = "0.1.37"
tokio = "1.26.0"
shuttle-persist = "0.46.0"
serde = { version = "1.0.203", features = ["derive"] }
