[package]
name = "command_vote"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
emoji.workspace = true
poise.workspace = true
poise_error.workspace = true
shared.workspace = true
