[package]
name = "command_timestamp"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
emoji.workspace = true
poise.workspace = true
poise_error.workspace = true
shared.workspace = true
