[package]
name = "config"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
database.workspace = true
emoji.workspace = true
shared.workspace = true
paste.workspace = true
poise.workspace = true
poise_error.workspace = true
serde.workspace = true
