[package]
name = "analytics"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
charts-rs.workspace = true
chrono.workspace = true
database.workspace = true
poise.workspace = true
poise_error.workspace = true
shared.workspace = true
