[package]
name = "command_updates"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
command_updates_proc_macro.workspace = true
poise.workspace = true
poise_error.workspace = true
shared.workspace = true
