name: CI/CD

on:
  push:
    branches: ["v1"]
  pull_request:
    branches: ["v1"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Spellcheck
        uses: crate-ci/typos@v1.29.4
      - name: Clippy
        run: cargo clippy --release --verbose

  cd:
    name: CD
    runs-on: self-hosted
    environment: production
    concurrency: production
    needs: ci
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JHKAYMCMR2ZP8GW5Q5109TPT
          cargo-shuttle-version: 0.53.0
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'
            TOPGG_TOKEN = '${{ secrets.TOPGG_TOKEN }}'
